server:
  port: 8883
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka,http://localhost:8882/eureka
#分别指向peer1，peer2进行注册
spring:
  application:
    name: Eureka-Client-Test
